### PR TITLE
Support for monitoring the analog alarms property

### PR DESCRIPTION
**Pull request by cnlklink**

### CODE REVIEW

**Review by rneswold — COMMENTED** [review]
I'm not sure I like this new function and `monitorDigitalStatus()` in the official API for this service. They are simply taking the stream from `monitorDevice()` and modifying the results with `.map()`.

Do we think other apps will find these specialty methods useful?

If not, they should be moved in the param page app.

**Comment by cnlklink** [comment]
I figured that this code belongs in the API because it has special knowledge of how to decode what is returned for the analog alarm property.  I don't think this is knowledge the applications should have.  I included an AnalogAlarmStatus type that the stream could return (which wasn't included in my original commit by mistake) which contains an enum that is either noAlarm, alarming, or bypassed.

But that begs the question.  What is returned for the analog alarm property?  If I were to decode this in the parameter page what should I expect to see?

**Comment by beauremus** [comment]
I'm not sure I follow everything here, but I wonder if the argument to put this here also leads us to change how the API presents the data. If we think everyone will have to do a transform, let's change this in the GraphQL resolver?

**Comment by cnlklink** [comment]
You're right, decoding from the raw data to the three states should exist at a lower-level than the Flutter library.  That said, IMHO the Flutter library still has a responsibility to map the basic type returned by the GraphQL API into a Flutter enum.  E.g., if the resolver returns the analog alarm state as strings such as "Alarm", "No Alarm" or "Bypassed" then the `monitorAnalogAlarm(..)` method should convert this string into an enum that gets placed into the Stream.  Double this if the return type is an int where the meaning is much harder to infer.

**Pull request merged**
