### PR TITLE
Pull authentication UI into `-core`

### LINKED ISSUE #27: Incorporate more/all Authentication responsibilities
The current version provides access to KeyCloak to authenticate the user. But now we're going to start another app and we realized that we're going to specify the login/logout interface again. Maybe there should be a standard interface to do this and it can be placed in `-core`.

This issue should be used to track suggestions for the UI which provide a standard way to login/logout and, maybe, a way to display the current authorized credentials.

### PR DESCRIPTION
**Pull request by rneswold**
This pull-request has `-core` create the left-side `Drawer`. The drawer's header now shows the user's login state along with a button to change it. A application no longer provides a `Drawer` to the scaffold but, instead, specifies a `List<ListTile>` parameter which will get added to the drawer.

### CODE REVIEW

**Comment by rneswold** [comment]
I don't want to merge this yet until @cnlklink and @madpolzin take a look.

**Comment by rneswold** [comment]
Demo-ed this current UI with @cnlklink. He mentioned that Material 3 has a navigation "rail" widget that he's using for the plot interface. It's a much sleeker design, so we'll get with @madpolzin to see what we need to generalize it in `-core`.

**Comment by cnlklink** [comment]
I'd like to try this out in the `wire-scanner-app` and then integrate it into `plotting-app` (probably trickier).

Or another approach is we promote the whole wide/narrow navigation rail / bar into the StandardApp as well?

**Comment by rneswold** [comment]
> we promote the whole wide/narrow navigation rail / bar into the StandardApp as well?

I think we could generalize this.

**Review by cnlklink — APPROVED** [review]

**Pull request merged**
